template-zip-file: refactor update-binary formatting and integrate build-time metadata injection
Improved script structure and formatting while adapting Root, ROM, and Build date fields for automated replacement by the build system

diff --git a/template-zip-file/META-INF/com/google/android/update-binary b/template-zip-file/META-INF/com/google/android/update-binary
--- a/template-zip-file/META-INF/com/google/android/update-binary
+++ b/template-zip-file/META-INF/com/google/android/update-binary
@@ -1,11 +1,11 @@
 #!/sbin/sh
 # Shell Script EDIFY Replacement: Recovery Flashable Zip
-# Credits to: osm0sis, salvogiangri, utkustnr/Frax3r, Simon1511, RisenID, saadelasfur, MySelly
+# Credits to: osm0sis, salvogiangri, Simon1511, RisenID, Frax3r, saadelasfur
 # See https://github.com/bone-machine/android_kernel_samsung_sm7325_a52s_5g
 
 OUTFD=/proc/self/fd/$2;
 ZIPFILE="$3";
-TMPDIR="/cache/rios";
+TMPDIR="/tmp/rios";
 
 package_extract_dir() {
   local entry outfile;
@@ -71,47 +71,75 @@ write_raw_image() { dd if="$1" of="$2"; }
 
 set_progress() { echo "set_progress $1" >> $OUTFD; }
 
-ui_print " ";
-ui_print "***************************************************";
-ui_print "* bone-machine's custom kernel for A52s 5G (AOSP) *";
-ui_print "* KernelSU-Next v3.2.0-legacy                     *";
-ui_print "* Credits: salvogiangri, Frax3r, Simon1511,       *";
-ui_print "* RisenID, saadelasfur, and MySelly               *";
-ui_print "***************************************************";
-ui_print " ";
+abort() {
+  ui_print " ";
+  ui_print "$1";
+  ui_print "Installation aborted.";
+  rm -rf "$TMPDIR";
+  exit 1;
+}
 
+ui_print " ";
+ui_print "    __                                    ";
+ui_print "   / /_  ____  ____  ___                  ";
+ui_print "  / __ \/ __ \/ __ \/ _ \                 ";
+ui_print " / /_/ / /_/ / / / /  __/__    _          ";
+ui_print "/_.___/\____/_/_/_/\___// /_  (_)___  ___ ";
+ui_print "  / __ \`__ \/ __ \`/ ___/ __ \/ / __ \/ _ \\";
+ui_print " / / / / / / /_/ / /__/ / / / / / / /  __/";
+ui_print "/_/ /_/ /_/\__,_/\___/_/ /_/_/_/ /_/\___/ ";
+ui_print "                                          ";
+ui_print "##########################################";
+ui_print " ";
+ui_print "Device:     Samsung Galaxy A52s 5G";
+ui_print "Codename:   a52sxq";
+ui_print "Root:       KernelSU-Next v3.2.0-legacy";
+ui_print "ROM:        AOSP";
+ui_print "Kernel:     Linux 5.4.289";
+ui_print "Compiler:   Clang 19";
+ui_print "Build date: 2026-06-04";
+ui_print " ";
+ui_print "Special thanks to salvogiangri, Simon1511,";
+ui_print "Frax3r, RisenID, and saadelasfur!";
+ui_print " ";
+ui_print "##########################################";
+ui_print " ";
 set_progress 0
 
 if ! getprop ro.boot.bootloader | grep -qE "A528"; then
-  ui_print "- Device is not an A52s 5G, aborting...";
-  exit 1;
+  abort "Unsupported device. This kernel is for A52s 5G only."
 fi
 
-ui_print "- Extracting images";
-mount -o rw,remount -t auto "/cache";
-mkdir -p $TMPDIR;
-package_extract_dir "images" "$TMPDIR/";
+ui_print "- Extracting images...";
+mkdir -p "$TMPDIR";
+package_extract_dir "images" "$TMPDIR/" || abort "Failed to extract images.";
 set_progress 10;
 
-ui_print "- Flashing boot.img...";
-write_raw_image "$TMPDIR/boot.img" "/dev/block/bootdevice/by-name/boot";
-set_progress 25;
+ui_print "- Verifying images...";
+for img in boot.img dtbo.img vendor_boot.img; do
+  [ -f "$TMPDIR/$img" ] || abort "Missing image: $img"
+done
+set_progress 20;
 
-ui_print "- Flashing dtbo.img...";
-write_raw_image "$TMPDIR/dtbo.img" "/dev/block/bootdevice/by-name/dtbo";
+ui_print "- Flashing boot.img";
+write_raw_image "$TMPDIR/boot.img" "/dev/block/bootdevice/by-name/boot" || abort "Failed to flash boot.img";
+set_progress 30;
+
+ui_print "- Flashing dtbo.img";
+write_raw_image "$TMPDIR/dtbo.img" "/dev/block/bootdevice/by-name/dtbo" || abort "Failed to flash dtbo.img";
 set_progress 50;
 
-ui_print "- Flashing vendor_boot.img...";
-write_raw_image "$TMPDIR/vendor_boot.img" "/dev/block/bootdevice/by-name/vendor_boot";
-set_progress 75;
+ui_print "- Flashing vendor_boot.img";
+write_raw_image "$TMPDIR/vendor_boot.img" "/dev/block/bootdevice/by-name/vendor_boot" || abort "Failed to flash vendor_boot.img";
+set_progress 70;
 
-ui_print "- Cleaning up...";
+ui_print "- Finalizing installation...";
 rm -rf "$TMPDIR";
 set_progress 90;
 
 ui_print " ";
-ui_print "Done! Enjoy the kernel!";
+ui_print "Installation complete.";
 ui_print " ";
-ui_print "Be sure to wipe cache/dalvik if you encounter any issues.";
+ui_print "First boot may take longer than usual.";
 ui_print " ";
 set_progress 100;
